<?php

use Illuminate\Database\Seeder;

class GeneralSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('basin')->insert([
            ['basin_name' => 'Sibolga', 'area' => 51636.39, 'sequence' => 1],
            ['basin_name' => 'North Sumatra', 'area' => 88728.54, 'sequence' => 2],
            ['basin_name' => 'Nias', 'area' => 9358.91, 'sequence' => 3],
            ['basin_name' => 'Central Sumatra', 'area' => 101681.89, 'sequence' => 4],
            ['basin_name' => 'Pendalian', 'area' => 2613.08, 'sequence' => 5],
            ['basin_name' => 'Mentawai', 'area' => 22788.98, 'sequence' => 6],
            ['basin_name' => 'Ombilin', 'area' => 1065.16, 'sequence' => 7],
            ['basin_name' => 'Bengkulu', 'area' => 36721.52, 'sequence' => 8],
            ['basin_name' => 'South Sumatra', 'area' => 120852.27, 'sequence' => 9],
            ['basin_name' => 'West Bangka', 'area' => 5862.33, 'sequence' => 10],
            ['basin_name' => 'West Natuna', 'area' => 71183.24, 'sequence' => 11],
            ['basin_name' => 'South Natuna', 'area' => 18726.92, 'sequence' => 12],
            ['basin_name' => 'Ujung Kulon', 'area' => 4139.45, 'sequence' => 13],
            ['basin_name' => 'Sunda Strait', 'area' => 1752.26, 'sequence' => 14],
            ['basin_name' => 'Sunda', 'area' => 19594.09, 'sequence' => 15],
            ['basin_name' => 'East Natuna', 'area' => 72444.03, 'sequence' => 16],
            ['basin_name' => 'Bangka', 'area' => 48565.65, 'sequence' => 17],
            ['basin_name' => 'Bogor', 'area' => 7068.76, 'sequence' => 18],
            ['basin_name' => 'South Java', 'area' => 42672.12, 'sequence' => 19],
            ['basin_name' => 'North West Java', 'area' => 23900.63, 'sequence' => 20],
            ['basin_name' => 'South West Java', 'area' => 7600.33, 'sequence' => 21],
            ['basin_name' => 'Vera', 'area' => 2875.75, 'sequence' => 22],
            ['basin_name' => 'Banyumas', 'area' => 8087.78, 'sequence' => 23],
            ['basin_name' => 'North Central Java', 'area' => 16986.42, 'sequence' => 24],
            ['basin_name' => 'Biliton', 'area' => 18236.13, 'sequence' => 25],
            ['basin_name' => 'South Central Java', 'area' => 5035.46, 'sequence' => 26],
            ['basin_name' => 'Melawi', 'area' => 20738.47, 'sequence' => 27],
            ['basin_name' => 'Ketungau', 'area' => 13884.11, 'sequence' => 28],
            ['basin_name' => 'East Java', 'area' => 98202.54, 'sequence' => 29],
            ['basin_name' => 'Pati', 'area' => 31492.98, 'sequence' => 30],
            ['basin_name' => 'North East Java', 'area' => 93843.51, 'sequence' => 31],
            ['basin_name' => 'South East Java', 'area' => 22472.62, 'sequence' => 32],
            ['basin_name' => 'Pembuang', 'area' => 8113.67, 'sequence' => 33],
            ['basin_name' => 'Lombok Bali', 'area' => 18231.48, 'sequence' => 34],
            ['basin_name' => 'Barito', 'area' => 41910.63, 'sequence' => 35],
            ['basin_name' => 'Kutai', 'area' => 121582.67, 'sequence' => 36],
            ['basin_name' => 'Asem Asem', 'area' => 9517.75, 'sequence' => 37],
            ['basin_name' => 'Kendilo', 'area' => 1638.34, 'sequence' => 38],
            ['basin_name' => 'Pasir', 'area' => 18540.76, 'sequence' => 39],
            ['basin_name' => 'Tarakan', 'area' => 46302.92, 'sequence' => 40],
            ['basin_name' => 'South Makassar', 'area' => 49064.06, 'sequence' => 41],
            ['basin_name' => 'Lariang', 'area' => 14562.22, 'sequence' => 42],
            ['basin_name' => 'Spermonde', 'area' => 13245.61, 'sequence' => 43],
            ['basin_name' => 'Flores', 'area' => 23285.41, 'sequence' => 44],
            ['basin_name' => 'West Sengkang', 'area' => 3846.18, 'sequence' => 45],
            ['basin_name' => 'Kalosi', 'area' => 4627.35, 'sequence' => 46],
            ['basin_name' => 'Sumba', 'area' => 11566.91, 'sequence' => 47],
            ['basin_name' => 'Minahasa', 'area' => 16931.38, 'sequence' => 48],
            ['basin_name' => 'Celebes', 'area' => 29275.4, 'sequence' => 49],
            ['basin_name' => 'Gorontalo', 'area' => 38138.38, 'sequence' => 50],
            ['basin_name' => 'Bone', 'area' => 51146.01, 'sequence' => 51],
            ['basin_name' => 'Sawu', 'area' => 52441.57, 'sequence' => 52],
            ['basin_name' => 'Banggai', 'area' => 38569.18, 'sequence' => 53],
            ['basin_name' => 'Manui', 'area' => 2947.56, 'sequence' => 54],
            ['basin_name' => 'Buton', 'area' => 6308.46, 'sequence' => 55],
            ['basin_name' => 'West Buru', 'area' => 34408.72, 'sequence' => 56],
            ['basin_name' => 'Tukang Besi', 'area' => 31886.48, 'sequence' => 57],
            ['basin_name' => 'Timor Sea', 'area' => 45496.75, 'sequence' => 58],
            ['basin_name' => 'Sula', 'area' => 12723.04, 'sequence' => 59],
            ['basin_name' => 'Sangihe', 'area' => 5660.1, 'sequence' => 60],
            ['basin_name' => 'Timor', 'area' => 10994.56, 'sequence' => 61],
            ['basin_name' => 'South Sula', 'area' => 10421.05, 'sequence' => 62],
            ['basin_name' => 'Wetar', 'area' => 6101.41, 'sequence' => 63],
            ['basin_name' => 'Buru', 'area' => 5526.46, 'sequence' => 64],
            ['basin_name' => 'Banda', 'area' => 76457.38, 'sequence' => 65],
            ['basin_name' => 'North Obi', 'area' => 13838.95, 'sequence' => 66],
            ['basin_name' => 'South Obi', 'area' => 5017.71, 'sequence' => 67],
            ['basin_name' => 'Weda Bay', 'area' => 22986.28, 'sequence' => 68],
            ['basin_name' => 'Kau Bay', 'area' => 7055.28, 'sequence' => 69],
            ['basin_name' => 'Weber', 'area' => 55230.07, 'sequence' => 70],
            ['basin_name' => 'Buli Bay', 'area' => 14759.48, 'sequence' => 71],
            ['basin_name' => 'Seram', 'area' => 13669.51, 'sequence' => 72],
            ['basin_name' => 'Salawati', 'area' => 9978.87, 'sequence' => 73],
            ['basin_name' => 'Berau', 'area' => 6522.89, 'sequence' => 74],
            ['basin_name' => 'Tanimbar', 'area' => 11910.45, 'sequence' => 75],
            ['basin_name' => 'Palung Aru', 'area' => 63197.41, 'sequence' => 76],
            ['basin_name' => 'Bintuni', 'area' => 30241.6, 'sequence' => 77],
            ['basin_name' => 'Cendrawasih', 'area' => 35476.46, 'sequence' => 78],
            ['basin_name' => 'Akimeugah', 'area' => 33952, 'sequence' => 79],
            ['basin_name' => 'Arafura', 'area' => 73779.11, 'sequence' => 80],
            ['basin_name' => 'Sahul', 'area' => 53191.26, 'sequence' => 81],
            ['basin_name' => 'Memberamo', 'area' => 21275.47, 'sequence' => 82],
            ['basin_name' => 'Biak', 'area' => 8749.75, 'sequence' => 83],
            ['basin_name' => 'Meervlakte', 'area' => 8903.56, 'sequence' => 84],
            ['basin_name' => 'Teer', 'area' => 5118.35, 'sequence' => 85],
            ['basin_name' => 'Iwur', 'area' => 13265.08, 'sequence' => 86],
            ['basin_name' => 'Passive Margin', 'area' => 506640.44, 'sequence' => 87],
        ]);

        DB::table('province')->insert([
            ['province_name' => 'Nanggroe Aceh Darussalam'],
            ['province_name' => 'Sumatra Utara'],
            ['province_name' => 'Sumatra Barat'],
            ['province_name' => 'Riau'],
            ['province_name' => 'Jambi'],
            ['province_name' => 'Sumatra Selatan'],
            ['province_name' => 'Bengkulu'],
            ['province_name' => 'Lampung'],
            ['province_name' => 'Kepulauan Bangka Belitung'],
            ['province_name' => 'Kepulauan Riau'],
            ['province_name' => 'Daerah Khusus Ibukota Jakarta'],
            ['province_name' => 'Jawa Barat'],
            ['province_name' => 'Jawa Tengah'],
            ['province_name' => 'Daerah Istimewa Yogyakarta'],
            ['province_name' => 'Jawa Timur'],
            ['province_name' => 'Banten'],
            ['province_name' => 'Bali'],
            ['province_name' => 'Nusa Tenggara Barat'],
            ['province_name' => 'Nusa Tenggara Timur'],
            ['province_name' => 'Kalimantan Barat'],
            ['province_name' => 'Kalimantan Tengah'],
            ['province_name' => 'Kalimantan Selatan'],
            ['province_name' => 'Kalimantan Timur'],
            ['province_name' => 'Sulawesi Utara'],
            ['province_name' => 'Sulawesi Tengah'],
            ['province_name' => 'Sulawesi Selatan'],
            ['province_name' => 'Sulawesi Tenggara'],
            ['province_name' => 'Gorontalo'],
            ['province_name' => 'Sulawesi Barat'],
            ['province_name' => 'Maluku'],
            ['province_name' => 'Maluku Utara'],
            ['province_name' => 'Papua'],
            ['province_name' => 'Papua Barat'],
        ]);

        // Migrate WK, Contractor, and PSC.
        $pscList = DB::connection('oldrps')->table('adm_working_area as wk')
            ->join('adm_psc as psc', 'wk.wk_id', '=', 'psc.wk_id')
            ->join('adm_kkks as kkks', 'psc.psc_id', '=', 'kkks.psc_id')
            ->select('wk.wk_id', 'wk.wk_name', 'wk.wk_shore', 'wk.wk_area_ori',
                'wk.wk_stage', 'kkks.kkks_id', 'kkks.kkks_name')
            ->whereNotIn('wk.wk_id', ['WK0000', 'WK9999'])
            ->orderBy('wk.wk_id')
            ->get();

        foreach ($pscList as $psc) {
            DB::transaction(function () use ($psc) {
                DB::table('working_area')->insert([
                    'id' => $psc->wk_id,
                    'working_area_name' => $psc->wk_name,
                    'shore' => $psc->wk_shore,
                    'area_original' => $psc->wk_area_ori,
                    'stage_original' => $psc->wk_stage,
                ]);

                $contractorId = DB::table('contractor')->insertGetId([
                    'contractor_name' => $psc->kkks_name,
                ]);

                DB::table('contractor_working_area')->insert([
                    'working_area_id' => $psc->wk_id,
                    'contractor_id' => $contractorId,
                    'rps_year' => '2014',
                    'interest' => 100,
                    'is_operator' => 1,
                ]);

                DB::table('user')->insert([
                    'working_area_id' => $psc->wk_id,
                    'role' => 'contractor',
                ]);
            });
        }

        DB::table('working_area')->insert([
            'id' => 'WK1099',
            'working_area_name' => 'PASANGKAYU',
            'shore' => 'Offshore',
            'stage_original' => 'Sudah Terminasi',
        ]);

        DB::table('working_area')->insert([
            'id' => 'WK1509',
            'working_area_name' => 'KAMPAR AREA',
            'shore' => 'Onshore',
            'stage_original' => 'Eksploitasi',
        ]);

        $marathonOil = DB::table('contractor')->insertGetId([
            'contractor_name' => 'Marathon Oil (Pasangkayu)',
        ]);

        $medcoKampar = DB::table('contractor')->insertGetId([
            'contractor_name' => 'Medco E&P Kampar'
        ]);

        DB::table('contractor_working_area')->insert([
            'working_area_id' => 'WK1099',
            'contractor_id' => $marathonOil,
            'rps_year' => '2014',
            'interest' => 100,
            'is_operator' => 1,
        ]);

        DB::table('contractor_working_area')->insert([
            'working_area_id' => 'WK1509',
            'contractor_id' => $medcoKampar,
            'rps_year' => '2014',
            'interest' => 100,
            'is_operator' => 1,
        ]);

        DB::table('user')->insert([
            ['working_area_id' => 'WK1099', 'role' => 'contractor'],
            ['working_area_id' => 'WK1509', 'role' => 'contractor'],
        ]);

        $formations = DB::connection('oldrps')->table('adm_formation')
            ->select('formation_name')
            ->orderBy('formation_name')
            ->get();

        foreach ($formations as $formation) {
            DB::table('formation')->insert(['formation_name' => $formation->formation_name]);
        }

        $basinWorkingAreas = [
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1001'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1002'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1003'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1004'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1257'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1008'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1010'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1011'],
            ['basin_name' => 'Banyumas', 'working_area_id' => 'WK1012'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1013'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1014'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1015'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1016'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1017'],
            ['basin_name' => 'Bengkulu', 'working_area_id' => 'WK1018'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1019'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1020'],
            ['basin_name' => 'Biliton', 'working_area_id' => 'WK1021'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1025'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1026'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1027'],
            ['basin_name' => 'Seram', 'working_area_id' => 'WK1028'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1029'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1030'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1031'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1032'],
            ['basin_name' => 'Bogor', 'working_area_id' => 'WK1033'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1034'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1035'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1037'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1040'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1041'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1042'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1043'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1044'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1224'],
            ['basin_name' => 'Banggai', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'North Central Java', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'North West Java', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'Salawati', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1047'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1048'],
            ['basin_name' => 'Pati', 'working_area_id' => 'WK1266'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1050'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1051'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1052'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1053'],
            ['basin_name' => 'Salawati', 'working_area_id' => 'WK1055'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1056'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1057'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1058'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1059'],
            ['basin_name' => 'Sunda', 'working_area_id' => 'WK1060'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1061'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1452'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1063'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1065'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1066'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1067'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1068'],
            ['basin_name' => 'Akimeugah', 'working_area_id' => 'WK1269'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1070'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1071'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1073'],
            ['basin_name' => 'Pati', 'working_area_id' => 'WK1074'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1075'],
            ['basin_name' => 'East Natuna', 'working_area_id' => 'WK1076'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1079'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1080'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1085'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1087'],
            ['basin_name' => 'North West Java', 'working_area_id' => 'WK1089'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1461'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1091'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1092'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1093'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1094'],
            ['basin_name' => 'Iwur', 'working_area_id' => 'WK1138'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1096'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1097'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1098'],
            ['basin_name' => 'Lariang', 'working_area_id' => 'WK1099'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1100'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1102'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1103'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1104'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1106'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1107'],
            ['basin_name' => 'Memberamo', 'working_area_id' => 'WK1108'],
            ['basin_name' => 'Salawati', 'working_area_id' => 'WK1110'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1112'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1115'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1116'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1117'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1118'],
            ['basin_name' => 'Bone', 'working_area_id' => 'WK1119'],
            ['basin_name' => 'Banggai', 'working_area_id' => 'WK1120'],
            ['basin_name' => 'Seram', 'working_area_id' => 'WK1121'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1122'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1124'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1125'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1126'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1127'],
            ['basin_name' => 'Sunda', 'working_area_id' => 'WK1128'],
            ['basin_name' => 'Lariang', 'working_area_id' => 'WK1129'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1132'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1133'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1134'],
            ['basin_name' => 'Lariang', 'working_area_id' => 'WK1049'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1136'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1137'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1007'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1140'],
            ['basin_name' => 'Timor Sea', 'working_area_id' => 'WK1069'],
            ['basin_name' => 'Timor Sea', 'working_area_id' => 'WK1300'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1143'],
            ['basin_name' => 'West Sengkang', 'working_area_id' => 'WK1146'],
            ['basin_name' => 'Buton', 'working_area_id' => 'WK1147'],
            ['basin_name' => 'Lariang', 'working_area_id' => 'WK1148'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1149'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1150'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1151'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1152'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1153'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1154'],
            ['basin_name' => 'Lariang', 'working_area_id' => 'WK1155'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1156'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1045'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1158'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1159'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1160'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1162'],
            ['basin_name' => 'Sunda', 'working_area_id' => 'WK1163'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1164'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1165'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1166'],
            ['basin_name' => 'East Natuna', 'working_area_id' => 'WK1167'],
            ['basin_name' => 'Ujung Kulon', 'working_area_id' => 'WK1168'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1169'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1170'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1171'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1172'],
            ['basin_name' => 'Bogor', 'working_area_id' => 'WK1173'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1174'],
            ['basin_name' => 'Palung Aru', 'working_area_id' => 'WK1175'],
            ['basin_name' => 'Timor', 'working_area_id' => 'WK1176'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1177'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1181'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1135'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1183'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1184'],
            ['basin_name' => 'Bone', 'working_area_id' => 'WK1185'],
            ['basin_name' => 'Buton', 'working_area_id' => 'WK1186'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1187'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1188'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1189'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1190'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1191'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1192'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1193'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1194'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1195'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1196'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1157'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1198'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1199'],
            ['basin_name' => 'Seram', 'working_area_id' => 'WK1200'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1201'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1202'],
            ['basin_name' => 'Salawati', 'working_area_id' => 'WK1142'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1197'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1205'],
            ['basin_name' => 'Banggai', 'working_area_id' => 'WK1206'],
            ['basin_name' => 'Ombilin', 'working_area_id' => 'WK1207'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1208'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1213'],
            ['basin_name' => 'Cendrawasih', 'working_area_id' => 'WK1214'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1215'],
            ['basin_name' => 'Salawati', 'working_area_id' => 'WK1216'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1217'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1218'],
            ['basin_name' => 'Memberamo', 'working_area_id' => 'WK1219'],
            ['basin_name' => 'Pasir', 'working_area_id' => 'WK1220'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1221'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1222'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1223'],
            ['basin_name' => 'Palung Aru', 'working_area_id' => 'WK1270'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1225'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1182'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1230'],
            ['basin_name' => 'South Obi', 'working_area_id' => 'WK1231'],
            ['basin_name' => 'Seram', 'working_area_id' => 'WK1232'],
            ['basin_name' => 'Palung Aru', 'working_area_id' => 'WK1233'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1239'],
            ['basin_name' => 'Sula', 'working_area_id' => 'WK1240'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1241'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1242'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1248'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1203'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1250'],
            ['basin_name' => 'Cendrawasih', 'working_area_id' => 'WK1251'],
            ['basin_name' => 'Cendrawasih', 'working_area_id' => 'WK1252'],
            ['basin_name' => 'Cendrawasih', 'working_area_id' => 'WK1253'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1254'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1255'],
            ['basin_name' => 'Lariang', 'working_area_id' => 'WK1256'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1141'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1258'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1204'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1260'],
            ['basin_name' => 'Ujung Kulon', 'working_area_id' => 'WK1261'],
            ['basin_name' => 'East Natuna', 'working_area_id' => 'WK1264'],
            ['basin_name' => 'East Natuna', 'working_area_id' => 'WK1265'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1090'],
            ['basin_name' => 'East Natuna', 'working_area_id' => 'WK1267'],
            ['basin_name' => 'Weda Bay', 'working_area_id' => 'WK1310'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1229'],
            ['basin_name' => 'Bone', 'working_area_id' => 'WK1271'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1272'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1273'],
            ['basin_name' => 'West Natuna', 'working_area_id' => 'WK1274'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1275'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1276'],
            ['basin_name' => 'Berau', 'working_area_id' => 'WK1293'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1294'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1295'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1296'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1297'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1298'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1299'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1249'],
            ['basin_name' => 'Tarakan', 'working_area_id' => 'WK1301'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1302'],
            ['basin_name' => 'South Obi', 'working_area_id' => 'WK1303'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1304'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1305'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1306'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1307'],
            ['basin_name' => 'Pembuang', 'working_area_id' => 'WK1308'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1309'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1259'],
            ['basin_name' => 'Timor', 'working_area_id' => 'WK1311'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1312'],
            ['basin_name' => 'Palung Aru', 'working_area_id' => 'WK1313'],
            ['basin_name' => 'Palung Aru', 'working_area_id' => 'WK1314'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1326'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1327'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1328'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1329'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1330'],
            ['basin_name' => 'Bogor', 'working_area_id' => 'WK1331'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1332'],
            ['basin_name' => 'Passive Margin', 'working_area_id' => 'WK1333'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1334'],
            ['basin_name' => 'Bintuni', 'working_area_id' => 'WK1335'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1337'],
            ['basin_name' => 'Mentawai', 'working_area_id' => 'WK1339'],
            ['basin_name' => 'East Natuna', 'working_area_id' => 'WK1340'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1450'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1451'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1095'],
            ['basin_name' => 'Vera', 'working_area_id' => 'WK1454'],
            ['basin_name' => 'Melawi', 'working_area_id' => 'WK1455'],
            ['basin_name' => 'Pembuang', 'working_area_id' => 'WK1456'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1457'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1458'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1459'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1460'],
            ['basin_name' => 'North Sumatra', 'working_area_id' => 'WK1062'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1462'],
            ['basin_name' => 'South Makassar', 'working_area_id' => 'WK1463'],
            ['basin_name' => 'Memberamo', 'working_area_id' => 'WK1464'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1470'],
            ['basin_name' => 'South Sumatra', 'working_area_id' => 'WK1471'],
            ['basin_name' => 'Pati', 'working_area_id' => 'WK1472'],
            ['basin_name' => 'East Java', 'working_area_id' => 'WK1473'],
            ['basin_name' => 'Kutai', 'working_area_id' => 'WK1474'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1475'],
            ['basin_name' => 'North East Java', 'working_area_id' => 'WK1501'],
            ['basin_name' => 'North West Java', 'working_area_id' => 'WK1502'],
            ['basin_name' => 'North West Java', 'working_area_id' => 'WK1503'],
            ['basin_name' => 'Timor Sea', 'working_area_id' => 'WK1504'],
            ['basin_name' => 'Barito', 'working_area_id' => 'WK1505'],
            ['basin_name' => 'Iwur', 'working_area_id' => 'WK1506'],
            ['basin_name' => 'Palung Aru', 'working_area_id' => 'WK1507'],
            ['basin_name' => 'Pembuang', 'working_area_id' => 'WK1508'],
            ['basin_name' => 'Central Sumatra', 'working_area_id' => 'WK1509'],
        ];

        foreach ($basinWorkingAreas as $basinWorkingArea) {
            DB::table('basin_working_area')->insert([
                'basin_name' => $basinWorkingArea['basin_name'],
                'working_area_id' => $basinWorkingArea['working_area_id']
            ]);
        }

        // TODO: WK selain WK0000 dan WK9999 dikarenakan provinsinya berisi 'Unknown',
        // Cari provinsi dari WK tersebut.
        $provinceWorkingAreas = DB::connection('oldrps')->table('rsc_play')
            ->join('adm_province', 'rsc_play.province_id', '=', 'adm_province.province_id')
            ->select('rsc_play.wk_id', 'adm_province.province_name')
            ->whereNotIn('rsc_play.wk_id', [
                'WK1049', 'WK1070', 'WK1148', 'WK1175', 'WK1186', 'WK1266', 'WK1331',
                'WK1340', 'WK1462', 'WK0000', 'WK9999'
            ])
            ->distinct()
            ->orderBy('rsc_play.wk_id')
            ->get();

        foreach ($provinceWorkingAreas as $province) {
            DB::table('province_working_area')->insert([
                'province_name' => $province->province_name,
                'working_area_id' => $province->wk_id,
            ]);
        }

        DB::table('archipelago')->insert([
            ['archipelago_name' => 'Sumatra'],
            ['archipelago_name' => 'Jawa'],
            ['archipelago_name' => 'Kalimantan'],
            ['archipelago_name' => 'Sulawesi'],
            ['archipelago_name' => 'Maluku'],
            ['archipelago_name' => 'Natuna'],
            ['archipelago_name' => 'Nusa Tenggara Timor'],
            ['archipelago_name' => 'Papua'],
        ]);

        $archipelagoWorkingAreas = [
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1001'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1002'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1003'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1004'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1257'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1008'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1010'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1011'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1013'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1014'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1015'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1016'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1017'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1019'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1020'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1025'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1026'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1027'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1028'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1029'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1030'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1031'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1032'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1033'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1034'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1035'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1037'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1040'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1041'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1042'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1043'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1044'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1224'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1047'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1048'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1266'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1050'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1051'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1052'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1053'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1055'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1056'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1057'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1058'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1059'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1060'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1061'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1452'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1063'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1065'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1066'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1067'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1068'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1269'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1070'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1071'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1073'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1074'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1075'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1076'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1079'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1080'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1085'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1087'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1089'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1461'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1091'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1092'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1093'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1094'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1138'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1096'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1097'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1098'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1099'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1100'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1102'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1103'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1104'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1106'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1107'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1108'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1110'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1112'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1115'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1116'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1117'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1118'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1119'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1120'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1121'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1122'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1124'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1125'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1126'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1127'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1128'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1129'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1132'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1133'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1134'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1049'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1136'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1137'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1007'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1140'],
            ['archipelago_name' => 'Nusa Tenggara Timor', 'working_area_id' => 'WK1069'],
            ['archipelago_name' => 'Nusa Tenggara Timor', 'working_area_id' => 'WK1300'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1143'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1147'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1148'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1149'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1150'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1151'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1152'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1153'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1154'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1155'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1156'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1045'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1158'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1159'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1160'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1162'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1163'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1164'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1165'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1166'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1167'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1168'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1169'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1170'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1171'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1172'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1173'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1174'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1175'],
            ['archipelago_name' => 'Nusa Tenggara Timor', 'working_area_id' => 'WK1176'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1177'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1181'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1135'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1183'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1184'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1185'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1186'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1187'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1188'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1189'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1190'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1191'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1192'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1193'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1194'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1195'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1196'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1157'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1198'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1199'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1200'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1201'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1202'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1142'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1197'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1205'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1206'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1207'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1208'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1213'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1214'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1215'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1216'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1217'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1218'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1219'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1220'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1221'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1222'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1223'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1270'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1225'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1182'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1230'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1231'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1232'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1233'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1239'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1241'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1242'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1248'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1203'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1250'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1251'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1252'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1253'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1254'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1255'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1256'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1141'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1258'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1204'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1260'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1261'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1264'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1265'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1090'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1267'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1310'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1229'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1271'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1272'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1273'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1274'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1275'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1276'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1293'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1294'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1295'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1296'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1297'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1298'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1299'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1249'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1301'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1302'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1303'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1304'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1305'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1306'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1307'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1309'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1259'],
            ['archipelago_name' => 'Nusa Tenggara Timor', 'working_area_id' => 'WK1311'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1312'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1313'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1314'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1326'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1327'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1328'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1329'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1330'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1331'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1332'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1333'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1334'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1335'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1337'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1339'],
            ['archipelago_name' => 'Natuna', 'working_area_id' => 'WK1340'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1450'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1451'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1095'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1454'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1455'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1457'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1458'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1459'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1460'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1062'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1462'],
            ['archipelago_name' => 'Sulawesi', 'working_area_id' => 'WK1463'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1464'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1470'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1471'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1472'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1473'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1474'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1475'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1501'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1502'],
            ['archipelago_name' => 'Jawa', 'working_area_id' => 'WK1503'],
            ['archipelago_name' => 'Nusa Tenggara Timor', 'working_area_id' => 'WK1504'],
            ['archipelago_name' => 'Kalimantan', 'working_area_id' => 'WK1505'],
            ['archipelago_name' => 'Papua', 'working_area_id' => 'WK1506'],
            ['archipelago_name' => 'Maluku', 'working_area_id' => 'WK1507'],
            ['archipelago_name' => 'Sumatra', 'working_area_id' => 'WK1509'],
        ];

        foreach ($archipelagoWorkingAreas as $archipelago) {
            DB::table('archipelago_working_area')->insert([
                'archipelago_name' => $archipelago['archipelago_name'],
                'working_area_id' => $archipelago['working_area_id']
            ]);
        }

        DB::table('sys_year')->insert([
            'rps_year' => '2015',
            'begin' => '2015-05-01',
            'end' => '2016-05-01',
            'is_active' => 1
        ]);
    }
}
